### ISSUE TITLE
Fails when parsing URLs with a space

### ISSUE THREAD

**Issue by orthecreedence** [fukamachi/fast-http#18]
See the test case below. It's not strictly good HTTP to pass a URI with non-escaped spaces, but this is fairly common to my knowledge.

```lisp
(ql:quickload '(:fast-http :babel))

(defpackage :fast-test
  (:use :cl))
(in-package :fast-test)

(let* ((str (format nil "GET /test?name=my name HTTP/1.1~c~c~c~c" #\return #\newline #\return #\newline))
       (data (babel:string-to-octets str))
       (http (fast-http:make-http-request))
       (parser (fast-http:make-parser
                 http
                 :header-callback (lambda (headers)
                                    (format t "headers: ~a~%" headers)))))
  (funcall parser data))
```

That can also be tested via the master version of Wookie:

```lisp
(ql:quickload :wookie)

(let ((wookie-config:*debug-on-error* t))
  (as:with-event-loop ()
    (wookie:start-server (make-instance 'wookie:listener :port 8090))))
```

```sh
curl '127.0.0.1:8090/test?myname=andrew lyon'
```

Thanks for taking a look!

**Comment by fukamachi** [comment]
That's interesting.

Since US-ASCII space is not allowed in URI strings (RFC 2396), I'm not sure how I should take this serious.
And it's hard to tell whether the rest of the request line is a part of URI or not, especially when parsing HTTP/0.9 because, in the spec, we can omit the HTTP version.

```
# Is this a GET request to "/test?name=my name" in HTTP/1.1
# or a request to "/test?name=my name HTTP/1.1" in HTTP/0.9?
GET /test?name=my name HTTP/1.1
...
```

I'm willing to fix this problem if there's a good way to do.
Do you have any ideas?

**Comment by orthecreedence** [comment]
Good points. My gut says to look for either a) the first instance of ` HTTP/x.x` or b) the end of the line (and assume v0.9). You could even only enable this via a keyword in `make-parser`, like `:allow-uri-spaces` (or even a more general `:relaxed-parsing` option).

I think the main problem is that nginx/apache (and probably others) have opted to handle this case, so although it goes against the spec, it's accepted as standard practice by users/clients.

I understand the desire to not break away from the spec though, so up to you.

**Comment by fukamachi** [comment]
It now allows to parse HTTP requests with a URI that contains non-escaped spaces, with almost no performance degradation.

```
;; Request to '/test?name=my name' in HTTP/0.9
GET /test?name=my name

;; Request to '/test?name=my name' in HTTP/1.1
GET /test?name=my name HTTP/1.1

;; Request to '/test?name=my name HTTP/1.1' in HTTP/1.0
GET /test?name=my name HTTP/1.1 HTTP/1.0
```

**Comment by orthecreedence** [comment]
Excellent, thanks!
