### ISSUE TITLE
Fails when headers has "Upgrade-Insecure-Requests: 1"

### ISSUE THREAD

**Issue by nightshade427** [fukamachi/fast-http#22]
Parse fails when headers has "Upgrade-Insecure-Requests: 1" (chrome by default sends this now)

Seems to die here when it parses "upgade" and then expects ":" right after?

https://github.com/fukamachi/fast-http/blob/master/src/parser.lisp#L303

**Comment by fukamachi** [comment]
Thank you for reporting.
Fixed at #23 by @Rudolph-Miller.

**Comment by nightshade427** [comment]
Thanks for fixing it so fast. :)
