### ISSUE TITLE
GET / HTTP/1.1 shows http-resource as "/ HTTP/1.1"

### ISSUE THREAD

**Issue by orthecreedence** [fukamachi/fast-http#24]
This is showing up in the tests as well. I tried opening the hood an poking around, but wasn't able to find exactly how the first line is cut up.

**Comment by fukamachi** [comment]
The latest fast-http requires the latest [proc-parse](http://github.com/fukamachi/proc-parse), which is included in Quicklisp 2015-08-04.
I suspect the versions of your fast-http and proc-parse are mismatch.

**Comment by orthecreedence** [comment]
You're right, I had an old version of proc-parse in my asdf dir. Thanks for the quick response!!
