### ISSUE TITLE
Server fails on URI "/ RTSP/1.0" contains an illegal character #\  at position 1

### ISSUE THREAD

**Issue by pyankoff** [fukamachi/fast-http#26]
Hello, I've got the following error, how can I find the request and illegal character which cause that?

```
220.200.24.189 - [18/Feb/2016:04:03:31 +00:00] "GET / HTTP/1.0" 200 381 "-" "-"
27.10.78.48 - [18/Feb/2016:04:03:32 +00:00] "OPTIONS / HTTP/1.0" 404 683 "-" "-"

debugger invoked on a FAST-HTTP.ERROR:CB-MESSAGE-COMPLETE in thread
#<THREAD "clack-handler-woo" RUNNING {1009FB7053}>:
  Callback Error: the message-complete callback failed
  URI "/ RTSP/1.0" contains an illegal character #\  at position 1.
```

Thank you.

**Comment by fukamachi** [comment]
Didn't it invoke a debugger or show up stack traces right after?

**Comment by pyankoff** [comment]
No, that was the last message, I've just reloaded the server.

**Comment by pyankoff** [comment]
I've been playing with different requests and found one which has the same effect:
```
curl http://localhost:3000/?^
```
Error:
```
Callback Error: the message-complete callback failed
  URI "/?^" contains an illegal character #\^ at position 2.
```
Btw, it only happens when I'm using WOO server. Should we move the issue there somehow?
Thanks!

**Comment by fukamachi** [comment]
The error is seems to be caused by QURI in Woo, however, I'm not sure it should be treated as an issue.

As a space and "^" are both not allowed to be in URI's, it's an intended behaviour.
What would you like to get from the URI?

**Comment by pyankoff** [comment]
Right, but the problem is that my server crashes and stops responding to normal requests after somebody sends this request. I'm not sure who this somebody is, maybe some type of crawler.
Basically, now anybody can crash my service by sending request with bad URI.
Can I do something to skip these erroneous requests? Or maybe prohibit these URIs? 
Thanks.

**Comment by fukamachi** [comment]
Start Woo with `:debug nil` option, then it returns 400 bad request for them.

**Comment by fukamachi** [comment]
Wait, it probably doesn't resolve the problem. I'm looking into it.

**Comment by fukamachi** [comment]
I fixed it at https://github.com/fukamachi/woo/commit/0900de0cc3a31a378567b2b37a19d77500b27ae7.
Please check with the latest Woo.

**Comment by pyankoff** [comment]
Thank you, everything works fine now.
