### ISSUE TITLE
Build fails in latest sbcl from git - bad HANDLER-BIND syntax

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/fast-http#28]
src/parser.lisp has this:

    (handler-bind ((match-failed
                     (lambda () (error 'expect-failed))))
      ...)

But handler-bind functions take one argument. The latest SBCL detects this problem and signals a compile-time warning, which breaks the build.

**Comment by quicklisp** [comment]
With the SBCL release next week, this will be a big problem for fast-http and the many libraries that depend on it.

**Comment by fukamachi** [comment]
Sorry, I missed this issue.
