### ISSUE TITLE
Does not build on SBCL 1.4.0 today

### ISSUE THREAD

**Issue by xach** [fukamachi/fast-http#34]
I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/fast-http/c212515526dd33712c281023b2d7b4e9f3e2d254/fast-http-20180110-git/src/parser.lisp
    ; in: DEFUN-SPEEDY PARSE-HEADER-FIELD-AND-VALUE
    ;     (FAST-HTTP.PARSER::EXPECT-FIELD-END
    ;      (FAST-HTTP.PARSER::SKIP-UNTIL-VALUE-START-AND
    ;       (SETF (FAST-HTTP.HTTP:HTTP-UPGRADE-P FAST-HTTP.HTTP:HTTP) T)
    ;       (LET ((FAST-HTTP.PARSER::VALUE-START #))
    ;         (PROC-PARSE:SKIP* (NOT #\Return))
    ;         (PROC-PARSE:ADVANCE)
    ;         (PROC-PARSE:SKIP #\Newline)
    ;         (FAST-HTTP.PARSER::CALLBACK-DATA :HEADER-FIELD FAST-HTTP.HTTP:HTTP
    ;                                          FAST-HTTP.PARSER:CALLBACKS
    ;                                          FAST-HTTP.PARSER::DATA
    ;                                          FAST-HTTP.PARSER::FIELD-START
    ;                                          FAST-HTTP.PARSER::FIELD-END)
    ;         (FAST-HTTP.PARSER::CALLBACK-DATA :HEADER-VALUE FAST-HTTP.HTTP:HTTP
    ;                                          FAST-HTTP.PARSER:CALLBACKS
    ;                                          FAST-HTTP.PARSER::DATA
    ;                                          FAST-HTTP.PARSER::VALUE-START (- # 2)))))
    ; --> IF FAST-HTTP.PARSER::HANDLE-OTHERWISE PROGN DO BLOCK LET SVREF LET THE 
    ; --> SB-KERNEL:DATA-VECTOR-REF SB-KERNEL:DATA-VECTOR-REF-WITH-OFFSET 
    ; ==>
    ;   (THE SIMPLE-VECTOR #:N-VECTOR-88)
    ; 
    ; caught WARNING:
    ;   Derived type of #:N-VECTOR-88 is (VALUES (SIMPLE-ARRAY CHARACTER (128)) &OPTIONAL), conflicting with its asserted type SIMPLE-VECTOR.
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

**Comment by fukamachi** [comment]
Thanks for reporting. The above commit fixes it.
