### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/fast-http#39]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 502a37715dcb8544cc8528b78143a942de662c5a

*fast-http-test* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A18083}>: no symbol named "FINALIZE-BUFFER" in "SMART-BUFFER"

```

*fast-http* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A18083}>: no symbol named "FINALIZE-BUFFER" in "SMART-BUFFER"

```

[Full log here](http://report.quicklisp.org/2021-06-21/failure-report/fast-http.html)

**Comment by fukamachi** [comment]
Sorry, it's because `smart-buffer:finalize-buffer` was renamed.
Probably fixed at https://github.com/fukamachi/smart-buffer/commit/b622a2b624201701b834e940bafb01685a2603c1.
